name: Meany Lodge
title: Meany Lodge
remote_theme: ronv/ultra

livereload: true
#baseurl:

defaults:
  - scope:
      path: "" # an empty string means all files
    values:
      layout: "default"

  - scope:
      path: "img"
    values:
      image: true

exclude:
  - Gemfile
  - Gemfile.lock
  - maps
  - reference
  - annual