#theme: jekyll-theme-minimal
#theme: jekyll-theme-leap-day
theme: jekyll-theme-dinky
#remote_theme: ronv/minimal

defaults:
  - scope:
      path: "" # an empty string means all files
    values:
      layout: "dinky"

  - scope:
      path: "img"
    values:
      image: true