theme: jekyll-theme-dinky

defaults:
  - scope:
      path: "Access" # an empty string here means all files in the project
    values:
      layout: "plain"

  - scope:
      path: "img"
    values:
      image: true