#theme: jekyll-theme-dinky
# okay, nice and clean, but superscript doesn't

#theme: jekyll-theme-leap-day
# decent, menus behavior a little odd

#remote_theme: jekyll-theme-xixia

#theme: jekyll-theme-minimal
#remote_theme: ronv/minimal

remote_theme: aksakalli/jekyll-doc-theme@gh-pages

livereload: true
baseurl: /History

defaults:
  - scope:
      path: "" # an empty string means all files
    values:
      layout: "docs"
    sectionid: docs
    seo:
      type: "WebPage"

  - scope:
      path: "img"
    values:
      image: true

exclude:
  - Gemfile
  - Gemfile.lock

collections:
  docs:
    permalink: /:collection/:path/
    output: true