theme: jekyll-theme-sidey
remote_theme: ronv/sidey

defaults:
  - scope:
      path: "" # an empty string means all files
    values:
      layout: "sidey"

  - scope:
      path: "img"
    values:
      image: true